version: "3.8"
services:
  devops-java-springboot-color:
    # image: "ghcr.io/pagopa/devops-java-springboot-color:snapshot-upgrade-java-21"
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: devops-java-springboot-color
    restart: always
    # environment:
    #   - MY_APP_COLOR=red
    ports:
      - "8080:8080"
