name: 🚀 Payments release

on:
  push:
    branches:
      - develop
      - uat
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
  workflow_dispatch:

jobs:
  payments-flow-release:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: 🔖 Checkout code
        # https://github.com/actions/checkout/releases/tag/v4.2.1
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          ref: ${{ github.ref_name }}

      - name: 🚀 release + docker + azdo
        # https://github.com/pagopa/github-actions-template/releases/tag/v1.19.0
        uses: pagopa/github-actions-template/payments-flow-release@37569377fa759368a01c1e7f40700b4118d65d0c
        with:
          current_branch: ${{ github.ref_name }}
          enable_azure_devops_step: 'false'
          azure_devops_project_url: 'https://dev.azure.com/pagopaspa/devopslab-projects'
          azure_devops_pipeline_name: 'devopslab-diego-deploy.deploy'
          azure_devops_pat: ${{ secrets.AZUREDEVOPS_PAT }}
          azure_template_parameters: |
            {
              "APPS": "[one-color]",
              "POSTMAN_BRANCH": "${{ github.ref_name }}"
            }
